# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-09 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0005_auto_20200209_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='timestamp',
            new_name='post_time',
        ),
    ]
