# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-09 21:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0006_auto_20200209_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
